language: bash

dist: xenial

services:
  - docker

stages:
  - test

before_install:
  - docker version
  - docker-compose version

script:
  - make
  - make up
  - ./scripts/wait.sh
  - docker-compose logs
  - make test
  - make down
  - echo -e "yes\nyes\nyes" | make clean

after_failure:
  - docker-compose config
  - docker-compose ps
  - docker-compose logs
