version: "3.5"

services:
  registry:
    image: registry:2
    restart: always
    # ports:
    #   - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`${HOST}`)"
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=le"
networks:
  net:
    name: ${NETWORK}
    external: ${NETWORK_EXTERNAL}
